project_name: logfmt2json
before:
  hooks:
  - rm -rf dist
  - make setup build test lint
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/ntindall/logfmt2json/cmd.version={{.Version}} -X github.com/ntindall/logfmt2json/cmd.commit={{.Commit}} -X github.com/ntindall/logfmt2json/cmd.date={{.Date}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
